import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

// SEED DATA
// 40+ crops, plants and flowers for the encyclopedia


const crops = [
    // ── GRAINS ──────────────────────────────
    {
        name: 'Maize',
        botanicalName: 'Zea mays',
        category: 'GRAIN',
        description: 'A staple cereal crop widely grown across Nigeria. Thrives in warm temperatures with adequate rainfall.',
        daysToHarvest: 90,
        plantingDepthCm: 5,
        spacingCm: 30,
        waterNeedsMm: 50,
        sunlight: 'FULL_SUN',
        climateZone: 'Tropical',
        soilTypes: ['LOAMY', 'SANDY'],
        companionPlants: ['Beans', 'Squash'],
        pestsAndDiseases: ['Fall armyworm', 'Maize weevil', 'Leaf blight'],
        plantingMonths: [3, 4, 9, 10],
        harvestMonths: [6, 7, 12, 1],
    },
    {
        name: 'Rice',
        botanicalName: 'Oryza sativa',
        category: 'GRAIN',
        description: 'A major food crop that grows best in flooded or waterlogged conditions. Common in Niger Delta and Benue.',
        daysToHarvest: 120,
        plantingDepthCm: 2,
        spacingCm: 20,
        waterNeedsMm: 120,
        sunlight: 'FULL_SUN',
        climateZone: 'Tropical',
        soilTypes: ['CLAY', 'LOAMY'],
        companionPlants: ['Azolla'],
        pestsAndDiseases: ['Rice blast', 'Brown planthopper', 'Stem borer'],
        plantingMonths: [4, 5, 6],
        harvestMonths: [8, 9, 10],
    },
    {
        name: 'Sorghum',
        botanicalName: 'Sorghum bicolor',
        category: 'GRAIN',
        description: 'Drought-resistant grain ideal for the dry north. Used for food, animal feed and local brewing.',
        daysToHarvest: 110,
        plantingDepthCm: 4,
        spacingCm: 25,
        waterNeedsMm: 30,
        sunlight: 'FULL_SUN',
        climateZone: 'Semi-arid',
        soilTypes: ['SANDY', 'LOAMY', 'CLAY'],
        companionPlants: ['Cowpea'],
        pestsAndDiseases: ['Striga weed', 'Midge', 'Aphids'],
        plantingMonths: [5, 6],
        harvestMonths: [9, 10],
    },
    {
        name: 'Millet',
        botanicalName: 'Pennisetum glaucum',
        category: 'GRAIN',
        description: 'Hardy grain crop that tolerates poor soils and low rainfall. A key crop in northern Nigeria.',
        daysToHarvest: 75,
        plantingDepthCm: 3,
        spacingCm: 20,
        waterNeedsMm: 25,
        sunlight: 'FULL_SUN',
        climateZone: 'Arid',
        soilTypes: ['SANDY', 'LOAMY'],
        companionPlants: ['Cowpea', 'Groundnut'],
        pestsAndDiseases: ['Downy mildew', 'Smut', 'Aphids'],
        plantingMonths: [6, 7],
        harvestMonths: [9, 10],
    },

    // ── TUBERS ──────────────────────────────
    {
        name: 'Cassava',
        botanicalName: 'Manihot esculenta',
        category: 'TUBER',
        description: 'Nigeria\'s most important root crop. Drought tolerant and can grow in poor soils. Staple food across the country.',
        daysToHarvest: 270,
        plantingDepthCm: 8,
        spacingCm: 100,
        waterNeedsMm: 30,
        sunlight: 'FULL_SUN',
        climateZone: 'Tropical',
        soilTypes: ['LOAMY', 'SANDY'],
        companionPlants: ['Maize', 'Cowpea'],
        pestsAndDiseases: ['Cassava mosaic disease', 'Mealybug', 'Whitefly'],
        plantingMonths: [3, 4, 5, 10, 11],
        harvestMonths: [12, 1, 2, 3],
    },
    {
        name: 'Yam',
        botanicalName: 'Dioscorea rotundata',
        category: 'TUBER',
        description: 'Culturally significant crop in Nigeria. Requires well-drained loamy soil and full sunlight.',
        daysToHarvest: 240,
        plantingDepthCm: 15,
        spacingCm: 100,
        waterNeedsMm: 45,
        sunlight: 'FULL_SUN',
        climateZone: 'Tropical',
        soilTypes: ['LOAMY'],
        companionPlants: ['Maize', 'Melon'],
        pestsAndDiseases: ['Yam mosaic virus', 'Nematodes', 'Beetles'],
        plantingMonths: [2, 3, 4],
        harvestMonths: [8, 9, 10, 11],
    },
    {
        name: 'Sweet Potato',
        botanicalName: 'Ipomoea batatas',
        category: 'TUBER',
        description: 'Fast-growing tuber crop rich in vitamins. Grows well in many soil types across Nigeria.',
        daysToHarvest: 100,
        plantingDepthCm: 10,
        spacingCm: 30,
        waterNeedsMm: 30,
        sunlight: 'FULL_SUN',
        climateZone: 'Tropical',
        soilTypes: ['SANDY', 'LOAMY'],
        companionPlants: ['Beans'],
        pestsAndDiseases: ['Sweet potato weevil', 'Leaf blight'],
        plantingMonths: [3, 4, 9],
        harvestMonths: [6, 7, 12],
    },

    // ── VEGETABLES ──────────────────────────
    {
        name: 'Tomato',
        botanicalName: 'Solanum lycopersicum',
        category: 'VEGETABLE',
        description: 'High-value vegetable with strong market demand. Needs consistent watering and pest management.',
        daysToHarvest: 75,
        plantingDepthCm: 1,
        spacingCm: 45,
        waterNeedsMm: 50,
        sunlight: 'FULL_SUN',
        climateZone: 'Tropical',
        soilTypes: ['LOAMY', 'SILTY'],
        companionPlants: ['Basil', 'Carrot', 'Pepper'],
        pestsAndDiseases: ['Tuta absoluta', 'Early blight', 'Whitefly', 'Fusarium wilt'],
        plantingMonths: [10, 11, 12, 1],
        harvestMonths: [1, 2, 3, 4],
    },
    {
        name: 'Pepper',
        botanicalName: 'Capsicum annuum',
        category: 'VEGETABLE',
        description: 'Essential ingredient in Nigerian cooking. Both hot and sweet varieties grow well in the tropics.',
        daysToHarvest: 80,
        plantingDepthCm: 1,
        spacingCm: 40,
        waterNeedsMm: 40,
        sunlight: 'FULL_SUN',
        climateZone: 'Tropical',
        soilTypes: ['LOAMY', 'SANDY'],
        companionPlants: ['Tomato', 'Basil'],
        pestsAndDiseases: ['Anthracnose', 'Aphids', 'Phytophthora'],
        plantingMonths: [3, 4, 9, 10],
        harvestMonths: [6, 7, 12, 1],
    },
    {
        name: 'Okra',
        botanicalName: 'Abelmoschus esculentus',
        category: 'VEGETABLE',
        description: 'Warm-season vegetable that thrives in Nigerian climate. Popular in soups and stews.',
        daysToHarvest: 60,
        plantingDepthCm: 2,
        spacingCm: 30,
        waterNeedsMm: 35,
        sunlight: 'FULL_SUN',
        climateZone: 'Tropical',
        soilTypes: ['LOAMY', 'SANDY', 'CLAY'],
        companionPlants: ['Pepper', 'Basil'],
        pestsAndDiseases: ['Okra mosaic virus', 'Flea beetle', 'Aphids'],
        plantingMonths: [3, 4, 5, 9],
        harvestMonths: [5, 6, 7, 11],
    },
    {
        name: 'Garden Egg',
        botanicalName: 'Solanum melongena',
        category: 'VEGETABLE',
        description: 'Also known as eggplant or aubergine. Widely grown in Nigeria for local consumption and export.',
        daysToHarvest: 80,
        plantingDepthCm: 1,
        spacingCm: 60,
        waterNeedsMm: 40,
        sunlight: 'FULL_SUN',
        climateZone: 'Tropical',
        soilTypes: ['LOAMY'],
        companionPlants: ['Pepper', 'Tomato'],
        pestsAndDiseases: ['Flea beetle', 'Mites', 'Phomopsis blight'],
        plantingMonths: [3, 9],
        harvestMonths: [6, 12],
    },
    {
        name: 'Waterleaf',
        botanicalName: 'Talinum triangulare',
        category: 'VEGETABLE',
        description: 'Fast-growing leafy vegetable common in South-West Nigeria. Very popular in soups.',
        daysToHarvest: 30,
        plantingDepthCm: 1,
        spacingCm: 15,
        waterNeedsMm: 60,
        sunlight: 'PARTIAL_SUN',
        climateZone: 'Tropical',
        soilTypes: ['LOAMY', 'SILTY'],
        companionPlants: ['Ugwu'],
        pestsAndDiseases: ['Root rot', 'Leaf spot'],
        plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        harvestMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    },
    {
        name: 'Ugwu (Fluted Pumpkin)',
        botanicalName: 'Telfairia occidentalis',
        category: 'VEGETABLE',
        description: 'Highly nutritious leafy vegetable grown for its leaves and seeds. Common in the South-East.',
        daysToHarvest: 45,
        plantingDepthCm: 5,
        spacingCm: 100,
        waterNeedsMm: 60,
        sunlight: 'FULL_SUN',
        climateZone: 'Tropical',
        soilTypes: ['LOAMY', 'CLAY'],
        companionPlants: ['Maize'],
        pestsAndDiseases: ['Powdery mildew', 'Fruit fly', 'Beetles'],
        plantingMonths: [3, 4, 9, 10],
        harvestMonths: [5, 6, 11, 12],
    },
    {
        name: 'Carrot',
        botanicalName: 'Daucus carota',
        category: 'VEGETABLE',
        description: 'Root vegetable that grows best in cooler highland areas of Nigeria like Jos Plateau.',
        daysToHarvest: 70,
        plantingDepthCm: 1,
        spacingCm: 8,
        waterNeedsMm: 35,
        sunlight: 'FULL_SUN',
        climateZone: 'Temperate',
        soilTypes: ['SANDY', 'LOAMY'],
        companionPlants: ['Tomato', 'Lettuce'],
        pestsAndDiseases: ['Carrot fly', 'Leaf blight', 'Nematodes'],
        plantingMonths: [10, 11, 12],
        harvestMonths: [1, 2, 3],
    },

    // ── LEGUMES ──────────────────────────────
    {
        name: 'Cowpea',
        botanicalName: 'Vigna unguiculata',
        category: 'LEGUME',
        description: 'Also called black-eyed beans. Drought resistant and fixes nitrogen in soil — great companion crop.',
        daysToHarvest: 65,
        plantingDepthCm: 5,
        spacingCm: 30,
        waterNeedsMm: 25,
        sunlight: 'FULL_SUN',
        climateZone: 'Tropical',
        soilTypes: ['SANDY', 'LOAMY'],
        companionPlants: ['Maize', 'Sorghum', 'Millet'],
        pestsAndDiseases: ['Aphids', 'Pod borer', 'Bruchid weevil'],
        plantingMonths: [6, 7],
        harvestMonths: [9, 10],
    },
    {
        name: 'Groundnut',
        botanicalName: 'Arachis hypogaea',
        category: 'LEGUME',
        description: 'Major oil crop and protein source. Important in northern Nigeria. Also called peanut.',
        daysToHarvest: 120,
        plantingDepthCm: 5,
        spacingCm: 15,
        waterNeedsMm: 30,
        sunlight: 'FULL_SUN',
        climateZone: 'Tropical',
        soilTypes: ['SANDY', 'LOAMY'],
        companionPlants: ['Millet', 'Sorghum'],
        pestsAndDiseases: ['Groundnut rosette virus', 'Leaf spot', 'Aphids'],
        plantingMonths: [5, 6],
        harvestMonths: [9, 10],
    },
    {
        name: 'Soybeans',
        botanicalName: 'Glycine max',
        category: 'LEGUME',
        description: 'High-protein legume used for food, oil and animal feed. Grows well in the middle belt.',
        daysToHarvest: 100,
        plantingDepthCm: 4,
        spacingCm: 10,
        waterNeedsMm: 40,
        sunlight: 'FULL_SUN',
        climateZone: 'Tropical',
        soilTypes: ['LOAMY', 'CLAY'],
        companionPlants: ['Maize'],
        pestsAndDiseases: ['Soybean rust', 'Pod borer', 'Cutworm'],
        plantingMonths: [6, 7],
        harvestMonths: [10, 11],
    },

    // ── FRUITS ──────────────────────────────
    {
        name: 'Watermelon',
        botanicalName: 'Citrullus lanatus',
        category: 'FRUIT',
        description: 'Popular and profitable fruit crop. Grows best in the dry season with irrigation.',
        daysToHarvest: 80,
        plantingDepthCm: 2,
        spacingCm: 150,
        waterNeedsMm: 50,
        sunlight: 'FULL_SUN',
        climateZone: 'Tropical',
        soilTypes: ['SANDY', 'LOAMY'],
        companionPlants: ['Corn', 'Radish'],
        pestsAndDiseases: ['Aphids', 'Powdery mildew', 'Cucumber beetle'],
        plantingMonths: [11, 12, 1, 2],
        harvestMonths: [2, 3, 4, 5],
    },
    {
        name: 'Banana',
        botanicalName: 'Musa acuminata',
        category: 'FRUIT',
        description: 'Perennial fruit crop that produces year-round. Very common in southern Nigeria.',
        daysToHarvest: 300,
        plantingDepthCm: 30,
        spacingCm: 300,
        waterNeedsMm: 80,
        sunlight: 'FULL_SUN',
        climateZone: 'Tropical',
        soilTypes: ['LOAMY', 'CLAY'],
        companionPlants: ['Yam', 'Cocoyam'],
        pestsAndDiseases: ['Panama disease', 'Banana weevil', 'Black sigatoka'],
        plantingMonths: [3, 4, 5],
        harvestMonths: [1, 2, 3],
    },
    {
        name: 'Pineapple',
        botanicalName: 'Ananas comosus',
        category: 'FRUIT',
        description: 'Tropical fruit that grows well across southern Nigeria. Low maintenance once established.',
        daysToHarvest: 540,
        plantingDepthCm: 10,
        spacingCm: 60,
        waterNeedsMm: 35,
        sunlight: 'FULL_SUN',
        climateZone: 'Tropical',
        soilTypes: ['SANDY', 'LOAMY'],
        companionPlants: [],
        pestsAndDiseases: ['Mealybug', 'Heart rot', 'Nematodes'],
        plantingMonths: [3, 4],
        harvestMonths: [8, 9, 10],
    },
    {
        name: 'Pawpaw',
        botanicalName: 'Carica papaya',
        category: 'FRUIT',
        description: 'Fast-fruiting tropical tree. Very popular in Nigeria. Rich in vitamins and enzymes.',
        daysToHarvest: 270,
        plantingDepthCm: 2,
        spacingCm: 250,
        waterNeedsMm: 45,
        sunlight: 'FULL_SUN',
        climateZone: 'Tropical',
        soilTypes: ['LOAMY', 'SANDY'],
        companionPlants: ['Basil'],
        pestsAndDiseases: ['Papaya ringspot virus', 'Mealybug', 'Anthracnose'],
        plantingMonths: [3, 4, 9],
        harvestMonths: [12, 1, 6],
    },

    // ── HERBS ──────────────────────────────
    {
        name: 'Basil',
        botanicalName: 'Ocimum basilicum',
        category: 'HERB',
        description: 'Aromatic herb used in cooking and as a natural pest repellent when grown near tomatoes.',
        daysToHarvest: 30,
        plantingDepthCm: 1,
        spacingCm: 20,
        waterNeedsMm: 30,
        sunlight: 'FULL_SUN',
        climateZone: 'Tropical',
        soilTypes: ['LOAMY'],
        companionPlants: ['Tomato', 'Pepper'],
        pestsAndDiseases: ['Fusarium wilt', 'Aphids'],
        plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        harvestMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    },
    {
        name: 'Scent Leaf',
        botanicalName: 'Ocimum gratissimum',
        category: 'HERB',
        description: 'Traditional Nigerian herb used in soups and for medicinal purposes. Very easy to grow.',
        daysToHarvest: 21,
        plantingDepthCm: 1,
        spacingCm: 30,
        waterNeedsMm: 30,
        sunlight: 'PARTIAL_SUN',
        climateZone: 'Tropical',
        soilTypes: ['LOAMY', 'CLAY', 'SANDY'],
        companionPlants: ['Ugwu', 'Waterleaf'],
        pestsAndDiseases: ['Aphids'],
        plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        harvestMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    },
    {
        name: 'Ginger',
        botanicalName: 'Zingiber officinale',
        category: 'HERB',
        description: 'Nigeria is one of the world\'s top ginger producers. Grown mainly in Kaduna and Nassarawa states.',
        daysToHarvest: 240,
        plantingDepthCm: 5,
        spacingCm: 20,
        waterNeedsMm: 60,
        sunlight: 'PARTIAL_SUN',
        climateZone: 'Tropical',
        soilTypes: ['LOAMY', 'SILTY'],
        companionPlants: ['Turmeric'],
        pestsAndDiseases: ['Rhizome rot', 'Bacterial wilt', 'Shoot borer'],
        plantingMonths: [3, 4, 5],
        harvestMonths: [11, 12],
    },
    {
        name: 'Turmeric',
        botanicalName: 'Curcuma longa',
        category: 'HERB',
        description: 'Valuable spice crop with growing market demand. Similar growing conditions to ginger.',
        daysToHarvest: 270,
        plantingDepthCm: 5,
        spacingCm: 30,
        waterNeedsMm: 50,
        sunlight: 'PARTIAL_SUN',
        climateZone: 'Tropical',
        soilTypes: ['LOAMY'],
        companionPlants: ['Ginger'],
        pestsAndDiseases: ['Rhizome rot', 'Leaf blotch'],
        plantingMonths: [4, 5],
        harvestMonths: [12, 1],
    },

    // ── FLOWERS ──────────────────────────────
    {
        name: 'Sunflower',
        botanicalName: 'Helianthus annuus',
        category: 'FLOWER',
        description: 'Grown for oil, seeds and ornamental use. A profitable cash crop with growing demand.',
        daysToHarvest: 80,
        plantingDepthCm: 3,
        spacingCm: 30,
        waterNeedsMm: 30,
        sunlight: 'FULL_SUN',
        climateZone: 'Tropical',
        soilTypes: ['LOAMY', 'SANDY'],
        companionPlants: ['Cucumber', 'Squash'],
        pestsAndDiseases: ['Aphids', 'Downy mildew', 'Stem rot'],
        plantingMonths: [10, 11, 3, 4],
        harvestMonths: [1, 2, 6, 7],
    },
    {
        name: 'Marigold',
        botanicalName: 'Tagetes erecta',
        category: 'FLOWER',
        description: 'Bright ornamental flower that also repels pests naturally. Great companion plant.',
        daysToHarvest: 50,
        plantingDepthCm: 1,
        spacingCm: 20,
        waterNeedsMm: 25,
        sunlight: 'FULL_SUN',
        climateZone: 'Tropical',
        soilTypes: ['LOAMY', 'SANDY', 'CLAY'],
        companionPlants: ['Tomato', 'Pepper', 'Carrot'],
        pestsAndDiseases: ['Spider mites', 'Powdery mildew'],
        plantingMonths: [1, 2, 10, 11],
        harvestMonths: [3, 4, 12, 1],
    },
    {
        name: 'Hibiscus (Zobo)',
        botanicalName: 'Hibiscus sabdariffa',
        category: 'FLOWER',
        description: 'Grown for its calyces used to make zobo drink. High commercial value and export potential.',
        daysToHarvest: 150,
        plantingDepthCm: 2,
        spacingCm: 60,
        waterNeedsMm: 35,
        sunlight: 'FULL_SUN',
        climateZone: 'Tropical',
        soilTypes: ['LOAMY', 'SANDY'],
        companionPlants: ['Cowpea'],
        pestsAndDiseases: ['Aphids', 'Flea beetle', 'Cercospora leaf spot'],
        plantingMonths: [6, 7],
        harvestMonths: [11, 12],
    },
    {
        name: 'Rose',
        botanicalName: 'Rosa hybrida',
        category: 'FLOWER',
        description: 'Ornamental flower with strong market demand for events and decoration.',
        daysToHarvest: 60,
        plantingDepthCm: 30,
        spacingCm: 60,
        waterNeedsMm: 40,
        sunlight: 'FULL_SUN',
        climateZone: 'Temperate',
        soilTypes: ['LOAMY'],
        companionPlants: ['Marigold', 'Lavender'],
        pestsAndDiseases: ['Black spot', 'Aphids', 'Spider mites'],
        plantingMonths: [10, 11],
        harvestMonths: [1, 2, 3],
    },
]

async function main() {
    console.log('Seeding crop encyclopedia...')

    // Delete existing crops so we can re-seed cleanly
    await prisma.crop.deleteMany()

    // Insert all crops one by one
    for (const crop of crops) {
        await prisma.crop.create({ data: crop })
        console.log(`  Added: ${crop.name}`)
    }

    console.log(`\nDone — ${crops.length} crops seeded successfully`)
}

main()
    .catch((e) => {
        console.error('Seed failed:', e)
        process.exit(1)
    })
    .finally(() => prisma.$disconnect())